# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='url',
        ),
    ]
